# Generated by Django 3.1.7 on 2022-07-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220728_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ordered', 'Ordered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=255),
        ),
    ]
